# Generated by Django 5.2.3 on 2025-06-18 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_departement_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Requis. 150 caractères ou moins. Lettres, chiffres, espaces et @/./+/-/_ seulement.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Saisissez un nom d’utilisateur valide. Il ne peut contenir que des lettres, des nombres, des espaces ou les caractères « @ », « . », « + », « - » et « _ ».', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
