# Generated by Django 5.2.3 on 2025-06-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, help_text='Les matricules commencent par INFO, EQ, ETT...', max_length=20),
        ),
    ]
