# Generated by Django 5.2.3 on 2025-06-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('contenu', models.TextField(max_length=2000)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('promotion', models.CharField(blank=True, max_length=100)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('tags', models.CharField(blank=True, help_text='Séparez les tags par des virgules', max_length=200)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
