# Generated by Django 5.2.3 on 2025-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='departement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='promotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=200),
        ),
    ]
