# Generated by Django 5.2.3 on 2025-07-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_publicationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='fichier',
        ),
        migrations.CreateModel(
            name='PublicationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='publications/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.publication')),
            ],
        ),
    ]
