# Generated by Django 5.2.3 on 2025-07-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_publication_fichier_publicationvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationvideo',
            name='video',
            field=models.FileField(help_text='Formats acceptés : mp4, avi, mov', upload_to='publications/videos/'),
        ),
        migrations.CreateModel(
            name='PublicationPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(help_text='Format accepté : pdf', upload_to='publications/pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='core.publication')),
            ],
        ),
    ]
