# Generated by Django 5.2.3 on 2025-07-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reponse_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reponse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
